config/routes.rb
Rails.application.routes.draw do
  #get 'tags/new', to: "tags#new"
  devise_for :authors
  #get 'books/index'
  #get 'books/new'
  #get 'books/create'
  #get 'books/show'
  # get 'books/update'
  # get 'books/destory'
  # get 'books/edit'

  root :to => "books#index"
  # get "books/:id/tags/booktag", to: "books#booktag"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do 
    collection do
      get :booktag
      post :asstag
    end
  end
  resources :tags
  resources :authors
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :author

    has_many :booktags
    has_many :tags, through: :booktags,  dependent: :destroy
    
    validates :title, presence: true
    validates :des, presence: true, length: { minimum: 10 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = current_author.books.all
  end

  def show
    @book = current_author.books.find(params[:id])
  end

  def new
    @book = current_author.books.new
  end

  def create
    @book  = current_author.books.new(book_params)

    if @book.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book  = current_author.books.find(params[:id])
  end

  def update
    @book  = current_author.books.find(params[:id])

    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book  = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  def booktag
    #@books  = Book.all
    #@tags = Tag.all

  end
  def asstag
    @book  = Book.find(params[:book_id])
    @tag  = Tag.find(params[:tag_id])

    @var = Booktag.new
    @var.book_id = @book.id
    @var.tag_id = @tag.id

    if @var.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :des)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/booktag.html.erb
<label for="Book">Choose Book:</label>


<%= form_tag(asstag_books_path, :method => "post") do %>

</br>
<%= select_tag "book_id", options_for_select(Book.all.pluck(:title, :id)) %>

</br>
<label for="Tag">Choose tag:</label>
</br>
<%= select_tag "tag_id", options_for_select(Tag.all.pluck(:name, :id)) %>

<button type="submit">Assign</button>


<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1> Edit Book</h1>
<%= form_with model: @book do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% @book.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :Description %><br>
      <%= form.text_area :des %><br>
      <% @book.errors.full_messages_for(:des).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/books/index.html.erb
<h1>Books List</h1>

<button><%= link_to "Add Books", new_book_path %></button>
<button><%= link_to "Add Tags", new_tag_path %></button>
<button type="button" class="btn btn-primary">
<%= link_to "Assign Tag", booktag_books_path %>
</button>
<table class="table">

    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Tag</th>
        <th scope="col">Button</th>
      </tr>
    </thead>
    <tbody>
    <% @books.each_with_index do |book, index| %>
      <tr>
        <th scope="row">
        <%= index+1 %>
        </th>
        <td>
        <%= book.title %>
        </td>
        <td>
        <% book&.tag&.last&.name %>
        <%= book.tag.pluck(:name) %>
        </td>
        <td>
            <button type="button" class="btn btn-danger">
            <%= link_to "Delete", book_path(book), method: :delete, data: {confirm: 'Are you sure?'} %>
            </button>
            <button type="button" class="btn btn-primary">
            <%= link_to "Edit", edit_book_path(book) %>
            </button>
            <button type="button" class="btn btn-primary">
            <%= link_to "Show", book_path(book) %>
            </button>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/books/new.html.erb
<h1>Add New Books</h1>

<%= form_with model: @book do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :Description %><br>
    <%= form.text_area :des %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><%= @book.des %></p>

<button><%= link_to "Back", books_path %></button>