config/routes.rb
Rails.application.routes.draw do
  #get 'tags/new', to: "tags#new"
  devise_for :authors
  #get 'books/index'
  #get 'books/new'
  #get 'books/create'
  #get 'books/show'
  # get 'books/update'
  # get 'books/destory'
  # get 'books/edit'

  root :to => "books#index"
  # get "books/:id/tags/booktag", to: "books#booktag"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do 
    collection do
      get :booktag
      post :asstag
    end
  end
  resources :tags
  resources :authors
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :booktags
    has_many :books, through: :booktags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order('created_at ASC')
  end
  
  def new
    @tag = Tag.new
  end

  def create
    @tag  = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @tag  = Tag.find(params[:id])
  end

  def edit
    @tag  = Tag.find(params[:id])
  end

  def update
    @tag  = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to tags_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag  = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path, status: :see_other
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<h1>Tags</h1>


<%= form_with model: @tag do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/tags/index.html.erb
<h1>Tag List</h1>

<table class="table">

    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Button</th>
      </tr>
    </thead>
    <tbody>
    <% @tags.each_with_index do |tag, index| %>
      <tr>
        <th scope="row">
        <%= index+1 %>
        </th>
        <td>
        <%= tag.name %>
        </td>
        <td>
            <button type="button" class="btn btn-danger">
            <%= link_to "Delete", tag_path(tag), method: :delete, data: {confirm: 'Are you sure?'} %>
            </button>
            <button type="button" class="btn btn-primary">
            <%= link_to "Edit", edit_tag_path(tag) %>
            </button>
            <button type="button" class="btn btn-primary">
            <%= link_to "Show", tag_path(tag) %>
            </button>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/tags/new.html.erb
<h1>Tags</h1>


<%= form_with model: @tag do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/tags/show.html.erb
<h1>Tag</h1>
<%= @tag.name %>


<button><%= link_to "Back", books_path %></button>