config/routes.rb
Rails.application.routes.draw do
  #get 'tags/new', to: "tags#new"
  devise_for :authors
  #get 'books/index'
  #get 'books/new'
  #get 'books/create'
  #get 'books/show'
  # get 'books/update'
  # get 'books/destory'
  # get 'books/edit'

  root :to => "books#index"
  # get "books/:id/tags/booktag", to: "books#booktag"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do 
    collection do
      get :booktag
      post :asstag
    end
  end
  resources :tags
  resources :authors
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :author

    has_many :booktags
    has_many :tags, through: :booktags,  dependent: :destroy
    
    validates :title, presence: true
    validates :des, presence: true, length: { minimum: 10 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = current_author.books.all
  end

  def show
    @book = current_author.books.find(params[:id])
  end

  def new
    @book = current_author.books.new
  end

  def create
    @book  = current_author.books.new(book_params)

    if @book.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book  = current_author.books.find(params[:id])
  end

  def update
    @book  = current_author.books.find(params[:id])

    if @book.update(book_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book  = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  def booktag
    #@books  = Book.all
    #@tags = Tag.all

  end
  def asstag
    @book  = Book.find(params[:book_id])
    @tag  = Tag.find(params[:tag_id])

    @var = Booktag.new
    @var.book_id = @book.id
    @var.tag_id = @tag.id

    if @var.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :des)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">Book App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"> <%= link_to "Log out", destroy_author_session_path, :method => :delete %><span class="sr-only">(current)</span></a>
      </li>
  </div>
</nav>